
USER = 'user'
MODERATOR = 'moderator'
ADMIN = 'admin'

ROLES = (
    (USER, 'Пользователь'),
    (MODERATOR, 'Модератор'),
    (ADMIN, 'Администратор')
)

MAX_ROLE_LENGTH = max(len(role[0]) for role in ROLES)
USERNAME_MAX_LENGTH = 150
FIRSTNAME_MAX_LENGTH = 150
LASTNAME_MAX_LENGTH = 150
NAME_MAX_LENGTH = 256
EMAIL_MAX_LENGTH = 254
CONFIRMATION_CODE_MAX_LENGTH = 150

NOT_ALLOWED_USERNAME = 'me'

MIN_REVIEW_SCORE = 1
MAX_REVIEW_SCORE = 10

SHORT_REVIEW_COMMENT = 15
